# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users)
  return users;
}
getUser(-1)
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
- The function getUser is not safe because it is missing all error handling! There are no catch blocks and no way to check the response. 

# Teacher Feedback
Score: 1/3
The answer is correct however put it in your own words. 